'\" -*- coding: us-ascii -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH maleks 1 "10 March 2012" 0.1.6 ""
.SH NAME
maleks \- lexicographic data browser
.SH SYNOPSIS
'nh
.fi
.ad l
\fBmaleks\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
'in \n(.iu-\nxu
.ad b
'hy
.SH Description
maleks a graphical browser of dictionary fiches, which enables browsing
and indexing fiches.
.PP
CTRL-E: accept text in edition panel and go to next fiche 
.PP
CTRL-H: accept text in hint panel and go to next fiche
.PP
CTRL-D: add next fiche to bookmarks
.PP
CTRL-R: open task register from file
.PP
CTRL-K: clone fiche
.PP
CTRL-V: show nearby fiches
.PP
CTRL-ENTER:
.PP
* if structure/entry/mulitlevel register is active: open selected element and go to lower level
.PP
* if focus is in edition panel: copy hint panel content into edition panel
.PP
* if hint register is active: go to entry register and optionally start targeted binary search for selected element of hint register
.PP
CTRL-\(ua: go to first fiche in selected element of entry register
.PP
CTRL-\(da: go to last fiche in selected element of entry register
.PP
CTRL-<: go left in binary search
.PP
CTRL->: go right in binary search
.PP
CTRL-[: go left in binary search and accept text in edition panel
.PP
CTRL-]: go right in binary search and accept text in edition panel
.PP
CTRL-B: switch on/off binary search - in hint register works as ENTER
.PP
CTRL-\(<-: navigation in entry history - previous element
.PP
CTRL-\(->: navigation in entry history - next element
.PP
CTRL-PgDn: scrolling of entry register on fiche level
.PP
CTRL-PgUp: scrolling of entry register on fiche level
.PP
ENTER:
.PP
* if hint register is active: go to entry register and optionally start targeted binary search for selected element of hint register
.PP
* if focus is in edition panel - accept fiche with text from edition panel as entry; if targeted binary search is active empty edition field is treated as target
.PP
* if focus is in search panel and entry register is active on entry level - works as CTRL-B
.PP
\(ua: go to previous fiche in register order if focus is in register and fiches are shown
.PP
\(da: go to next fiche in register order if focus is in register and fiches are shown
.SH "Environment variables"
.TP 
\*(T<\fIXDG_CONFIG_HOME\fR\*(T>
Base directory for configuration files. The default is \*(T<\fI$HOME/.config\fR\*(T>.

See 
.URL http://standards.freedesktop.org/basedir-spec/latest/ "XDG Base Directory Specification"
for details.
.SH Files
.TP 
\*(T<\fI$XDG_CONFIG_HOME/maleks/maleks.conf\fR\*(T>
maleks configuration file
.SH "See also"
\fBdjvu\fR(1)
